FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get --assume-yes install postgresql-client

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

COPY ./scrapyproject/spiders/sreality.py .

CMD ["scrapy", "crawl", "sreality"]
