FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get --assume-yes install postgresql-client

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

COPY ./server.py .

CMD [ "python", "server.py" ]